import Head from "next/head";
import React from "react";

const index = () => {
  return (
    <>
      <Head>
        <title>Introduce || Redux & Next.js:-Register </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>this is register page </h1>
      </main>
    </>
  );
};

export default index;
