import ProductCard from "@/components/product/ProductCard";
import Head from "next/head";
import React, { useEffect, useState } from "react";

const index = () => {
  const [products, setProducts] = useState([]);
  useEffect(() => {
    fetch("http://localhost:3000/api/allProduct")
      .then((res) => res.json())
      .then((data) => setProducts(data.data));
  }, []);
  let view;
  if (!products.length) {
    view = <p>Loading.....</p>;
  } else {
    view = products.map((product, i) => (
      <ProductCard key={i} product={product} />
    ));
  }
  return (
    <>
      <Head>
        <title>Introduce || Redux & Next.js:-About </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-4 max-w-7xl mx-auto gap-5 mt-5">
        {view}
      </main>
    </>
  );
};

export default index;
