import Head from "next/head";
import { Inter } from "next/font/google";
import { useSelector } from "react-redux";
import ProductCard from "@/components/product/ProductCard";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const store = useSelector((store) => store);
  console.log(store);
  let addToCard;
  if (store?.card?.length) {
    addToCard = store.card.map((product, i) => (
      <ProductCard key={i} product={product} />
    ));
  }
  return (
    <>
      <Head>
        <title>Introduce || Redux & Next.js </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-7xl mx-auto grid  grid-cols-4 gap-5">
        {addToCard}
      </main>
    </>
  );
}
